@startuml
title pitaya_constants
legend
<u><b>Legend</b></u>
Render Aggregations: true
Render Fields: true
Render Methods: true
Private Aggregations: false
end legend
namespace constants {
    class propagateKey << (S,Aquamarine) >> {
    }
}



@enduml
